create table pets
(
    id          bigint auto_increment
        primary key,
    name        varchar(255)                        not null,
    breed       varchar(255)                        null,
    image       varchar(255)                        null,
    difficulty  int                                 null,
    behavior    varchar(255)                        null,
    ferocious   int                                 null,
    space       int                                 null,
    `group`     int                                 null,
    description varchar(255)                        null,
    created_at  timestamp default CURRENT_TIMESTAMP null,
    updated_at  timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
    deleted_at  datetime(6)                         null
);

INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (1, 'Abyssinian', 'Abyssinian', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867706/x1fkn2qbis6mfxzguc8z.jpg', 4, 'Energetic, curious, intelligent, and loves high places.', 2, 3, 1, 'Abyssinians are active and extremely curious cats that enjoy climbing and observing their surroundings from above. They are intelligent, trainable, and thrive in stimulating environments to avoid boredom.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (2, 'American Bobtail', 'American Bobtail', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867825/w0p1ngdcppqqc3ly4obr.jpg', 5, 'Friendly, playful, sometimes mischievous.', 3, 4, 2, 'Known for their short tails and dog-like personalities, American Bobtails are intelligent, social, and affectionate. They are great companions for families and enjoy interactive play.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (5, 'Bengal', 'Bengal', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867898/yimywhuj8wdp3javtxxp.jpg', 7, 'Energetic, active, and loves physical activities.', 6, 8, 3, 'Bengals have a wild appearance with striking coat patterns. They are affectionate but require a lot of physical activity and mental stimulation to stay happy and healthy.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (6, 'Birman', 'Birman', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867928/dbupwbm2xvj3p8fwzh1h.jpg', 3, 'Gentle, loyal, and affectionate.', 2, 3, 1, 'Birmans are quiet and loving cats that enjoy cuddling and staying close to their families. They are known for their blue eyes and silky coats, and they adapt well to calm homes.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (7, 'Bombay', 'Bombay', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867954/gf7lyqgylxhpaitjotpr.jpg', 4, 'Curious, affectionate, and loving.', 3, 3, 2, 'Bombays are sleek black cats with golden eyes. They are social, enjoy attention, and love being close to their humans, making them ideal for interactive homes.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (8, 'British Shorthair', 'British Shorthair', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744867983/dcyt27tjnk74s4zh1ogm.jpg', 2, 'Calm, independent, and easy-going.', 2, 4, 1, 'British Shorthairs are sturdy cats with plush coats and round faces. They are quiet, undemanding, and make excellent companions for apartment living or busy owners.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (9, 'Egyptian Mau', 'Egyptian Mau', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868013/muiggpys01ndteug6k8y.jpg', 6, 'Agile, alert, and adventurous.', 5, 5, 3, 'Egyptian Maus are one of the fastest domestic cats, easily recognized by their spotted coats. They are intelligent, active, and thrive in homes that allow exploration.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (10, 'Exotic Shorthair', 'Exotic Shorthair', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868031/ajs4fyiudl2kzdyejuvc.jpg', 2, 'Quiet, affectionate, and cuddly.', 1, 3, 1, 'A short-haired version of the Persian, Exotic Shorthairs are sweet, calm cats that love being held. They are low-maintenance and adapt well to relaxed households.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (11, 'Maine Coon', 'Maine Coon', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868191/lnm3beq8kcliga22wtza.jpg', 4, 'Gentle, patient, and intelligent.', 2, 8, 3, 'Maine Coons are large, majestic cats known for their friendly and playful demeanor. They are highly trainable and need ample space to move around comfortably.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (12, 'Manx', 'Manx', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868241/rindd5za6aptzrsknazw.jpg', 5, 'Loyal, clever, and affectionate.', 3, 4, 2, 'Manx cats are famous for their tailless or short-tailed appearance. They are intelligent, playful, and bond closely with their families, often following them like dogs.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (13, 'Norwegian Forest', 'Norwegian Forest', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868276/vzo1ztkouq52jvwdc9nv.jpg', 6, 'Calm, strong, and independent.', 4, 7, 3, 'Originating from Scandinavia, these cats have dense coats suited for cold climates. Norwegian Forest Cats are gentle giants that love climbing and need outdoor access or large indoor spaces.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (14, 'Persian', 'Persian', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868300/b7af98bpk1jiuuzyllet.jpg', 3, 'Quiet, elegant, and laid-back.', 1, 4, 1, 'Persians are known for their luxurious long coats and calm nature. They prefer peaceful environments, require regular grooming, and enjoy lounging around the home.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (15, 'Ragdoll', 'Ragdoll', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868322/c0hvj6orglc1zebugixa.jpg', 2, 'Gentle, docile, and friendly.', 1, 5, 1, 'Ragdolls go limp when picked up, hence the name. They are affectionate and relaxed, perfect for families with children or elderly owners seeking a calm companion.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (16, 'Russian Blue', 'Russian Blue', 'http://res.cloudinary.com/duwta75bz/image/upload/v1746589027/pvveplmye8590ltvlj5j.jpg', 3, 'Shy with strangers but loyal to family.', 1, 3, 2, 'Russian Blues have elegant silver-blue coats and bright green eyes. They are reserved around new people but very affectionate once bonded, thriving in quiet households.', '2025-04-17 12:08:40', '2025-05-07 10:37:27', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (17, 'Scottish Fold', 'Scottish Fold', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868363/u4ng5xwkkyhpyquj1ddg.jpg', 2, 'Sweet, lovable, and calm.', 1, 3, 1, 'Scottish Folds are best known for their distinctive folded ears. They are easy-going, affectionate, and enjoy being close to their humans without being overly demanding.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (18, 'Siamese', 'Siamese', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868378/sw7krs6ecbrk4hbxra4z.jpg', 6, 'Vocal, intelligent, and people-oriented.', 4, 4, 3, 'Siamese cats are highly vocal and expressive. They form strong bonds with their owners, crave attention, and are happiest in interactive, socially stimulating environments.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (19, 'Sphynx', 'Sphynx', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868398/s0fd0hqktnhvcqgen9ha.jpg', 8, 'Outgoing, curious, and affectionate.', 5, 5, 3, 'Sphynx cats are hairless, needing skin care and warmth. Despite their looks, they are incredibly friendly, loving, and seek constant companionship with their humans.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (20, 'Turkish Angora', 'Turkish Angora', 'https://res.cloudinary.com/duwta75bz/image/upload/v1744868465/tpjuf4lwjatkcfuzbkty.jpg', 5, 'Energetic, smart, and independent.', 4, 4, 2, 'Turkish Angoras are elegant cats known for their silky coats and spirited personality. They are intelligent, agile, and enjoy leading their own lives while being affectionate at times.', '2025-04-17 12:08:40', '2025-04-17 12:41:14', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (21, 'Lykoi', 'Lykoi', 'http://res.cloudinary.com/duwta75bz/image/upload/v1746588377/ca6kzgtaa22qhfqeeauo.jpg', 3, 'Playful, affectionate, and dog-like in loyalty.', 3, 2, 1, 'The Lykoi, also known as the "werewolf cat", has a unique appearance with sparse fur. They are very playful, social, and often described as having dog-like behaviors.', '2025-05-07 10:12:26', '2025-05-07 10:28:12', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (22, 'Singapura', 'Singapura', 'http://res.cloudinary.com/duwta75bz/image/upload/v1746588440/isn7ke19ajoksresi3og.jpg', 5, 'Active, curious, affectionate, and very small.', 1, 2, 1, 'Singapura cats are one of the smallest cat breeds. They are affectionate, inquisitive, and love to interact with their owners. Their petite size makes them ideal for apartment living.', '2025-05-07 10:12:26', '2025-05-07 10:28:12', null);
INSERT INTO petshop.pets (id, name, breed, image, difficulty, behavior, ferocious, space, `group`, description, created_at, updated_at, deleted_at) VALUES (23, 'Tuxedo', 'Tuxedo', 'http://res.cloudinary.com/duwta75bz/image/upload/v1746588485/ibnfzimhwao5cidhazkv.jpg', 2, 'Charming, clever, independent yet friendly.', 2, 2, 1, 'Tuxedo cats are not a breed but a color pattern. They are known for their intelligence and charm. They often exhibit playful and independent behaviors, while still forming strong bonds with humans.', '2025-05-07 10:12:26', '2025-05-07 10:28:12', null);
